### ISSUE TITLE
Finding 'exe' directory (Windows Server OS)

### ISSUE THREAD

**Issue by j-sabrsula** [nickrod518/PowerShell-Scripts#2] opened 2016-04-06 21:22 UTC
This may not be an issue so much as unexpected behavior for the lay person- 

OS: Windows Server 2012 R2
Powershell version: 4
Issue: Using the variable $PSScriptRoot in the powershell script before exe wrapping (the system variable normally stores root directory where script is executed from). 
Expected behavior: Variable stores path where powershell file is ran from (which works, but not as you'd think).
Observed behavior: Variable stores temp variable path where exe extracts to, under C:\Users<user>\AppData\Local\Temp\2\IXP001.TMP. (also where powershell file is found and left there after the exe completes). 

Ideally this copied ps1 file would be cleaned up by the exe once the process completes, i'd imagine. 

Having a way to reference where the exe ran from inside the powershell script would be nice as well, but I can't imagine a powershell script can talk outside the exe's scope. 
Running [Reflection.Assembly]::GetExecutingAssembly().Location displays a 'blank' in the location field as well. 

Script to test:
![image](https://cloud.githubusercontent.com/assets/11077362/14333279/77dd2a8e-fc13-11e5-8aa9-6d2af48fb233.png)

Output (log files removed up):
![image](https://cloud.githubusercontent.com/assets/11077362/14333284/85c4bfc2-fc13-11e5-9515-f17ab0de0b28.png)

**Comment by nickrod518** [comment] 2016-04-19 17:51
If I'm understanding you, you want $PSScriptRoot to return the path the exe was run from, or some way to reference that location. Everything appears to run as intended as it is right now, because as you said, the script is extracted to a temporary location and run from that location. You can think of the exe like a self-extracting zip file. I think this is expected iexpress behavior and what you're asking for is a new feature. 

One way to get the path you want is to build logic into your script that will get the process of the exe and its path. Something like:
`$EXERoot = Get-Process MyTest.exe | Select-Object Path`

I think another way would be for the command that calls the PS script to also pass it the path as a parameter (lines 442 and 447). Before I spend time on this, am I understanding you correctly?

**Comment by j-sabrsula** [comment] 2016-04-19 18:03
The benefit of $PSScriptRoot was it allowed access to source location of where the file is ran from. For example, if a script were to output some text files (i.e. logs), using $PSScriptRoot in a PS script would let you know the path the .ps1 was ran from to apply the files to the same location. Sort of allowing more portability.  As you've stated, that functionality gets lost when it's wrapped in the exe due to iexpress, and I do not expect that to change just to accommodate powershell scripts. 

While I do like the idea of storing the source path for possible use when the exe was created, it doesn't solve the 'anywhere' capacity that I was trying to implement, as this and other scripts like it would be used on other servers with possibly dissimilar file systems. What would be ideal is a way to reference the $PSScriptRoot path equivalent, in theory, but without manually recurring through the whole drive, I'm not aware of a smart way to achieve this.

**Comment by nickrod518** [comment] 2016-04-19 18:06
The one issue I see with replacing $PSScriptRoot with the pseudo root of the exe is that if someone uses supplementary files with this tool, those can't be referenced by relative path anymore. I don't think it would be difficult to add the exe's path (%~dp0) as a parameter passed to your script, but you'd still have to add the logic in your script to accept and do something with that, know what I mean?

**Comment by j-sabrsula** [comment] 2016-04-19 19:47
Yes, that seems to be the case. Powershell doesn't interpret %~dp0 directly, as a a batch script would, as far as I can tell. You'd have to pass something to it. Not to put a pipe dream out there, but I just wish there was a way not to have to use an additional external file to accomplish this behavior. I appreciate you responding to help confirm this situation.

**Comment by nickrod518** [comment] 2016-04-20 14:25
I haven't given up on it yet. I messed around yesterday with %~dp0 and %cd%, but that only returned the temp directory. I think the way to do this is to catch the process's path and pass that, but I'm still trying to figure out how exactly to do that as my CMD syntax isn't great.

**Comment by nickrod518** [comment] 2016-04-20 17:49
I've made some progress but I'm not sure if it will break anything else. Try replacing line 447 with:

`Add-Content $sed "AppLaunched=cmd /c for /f `"skip=1 tokens=1* delims=`" %i in (`'wmic process where `"name=`'$target.exe`'`" get ExecutablePath`') do PowerShell -ExecutionPolicy Bypass -File `"$PSScriptName`" %i & exit"`

And you'll also need to add something to your script that will take the exe path param it's being passed. Something like param($EXEPath) at the top should work.

**Comment by j-sabrsula** [comment] 2016-04-20 18:21
First up, that one liner is doing some serious work. Appending something to the sed file does seem like the right idea. That said, i'm a bit mixed up-

Line 447 shows up as the closing backet 
![image](https://cloud.githubusercontent.com/assets/11077362/14685313/bdcb971a-06f9-11e6-88e2-8443dac5cc96.png)

so I tried inserting that command above 447.
![image](https://cloud.githubusercontent.com/assets/11077362/14685326/ca68bf84-06f9-11e6-8a64-8dc9131d8dff.png)

As of now, i'm trying to get the exepath to show up, but even on a simple script like this, I can't get it to display when run as an exe with this modified code. Did I insert this command in the wrong spot?
![image](https://cloud.githubusercontent.com/assets/11077362/14685537/7dcdf2f6-06fa-11e6-81cc-12cd5554db84.png)
![image](https://cloud.githubusercontent.com/assets/11077362/14685569/90aec864-06fa-11e6-85df-ef9ff84865dd.png)

**Comment by nickrod518** [comment] 2016-04-20 18:32
My bad, I must be looking at a newer version. You want to replace 444 according to the latest version on GitHub. Also, replace line 439 with:

`Add-Content $sed "PostInstallCmd=cmd /c for /f `"skip=1 tokens=1* delims=`" %i in (`'wmic process where `"name=`'$target.exe`'`" get ExecutablePath`') do PowerShell -ExecutionPolicy Bypass -File `"$PSScriptName`" %i & exit"`

**Comment by j-sabrsula** [comment] 2016-04-20 18:51
When I replaced both changes to the applaunchd and postinstallcmd sections, I got the below output as an exe:
![image](https://cloud.githubusercontent.com/assets/11077362/14686243/7c2cbfec-06fd-11e6-8146-73ad8ae9eeba.png)

![image](https://cloud.githubusercontent.com/assets/11077362/14686238/75179c04-06fd-11e6-8476-b2279ba5fd4f.png)

The replaced code:
![image](https://cloud.githubusercontent.com/assets/11077362/14686338/ded5a5be-06fd-11e6-95cb-0d5894500695.png)

Which is great in that it is displaying the output, just not quite as trimmed as I'd imagine is intended. Is there more code that was replaced somewhere that got the trimmed output only, possibly?

**Comment by nickrod518** [comment] 2016-04-20 21:12
I think it might actually be working as intended. Check this out:

![image](https://cloud.githubusercontent.com/assets/2184955/14690696/5340b912-071b-11e6-96b4-319a5dcf17b2.png)

You can see that it's giving you the path to the exe with no problem. Maybe it's just a little confusing because the first line you see is what's actually run by the exe?

I did change the lines slightly. At the end where you have 
`%i` 
it needs to be 

```
`"%i`"
```

**Comment by j-sabrsula** [comment] 2016-04-20 21:34
Yes, I do think I see what you mean, I had thought at first that $exepath was the whole thing, but it's actually just what we want. Which is correct, that part is working as intended. Only now, the command before it (ran from the exe itself) appears to run at the start of all scripts, which isn't quite perfect. Is there a command to suppress output (from writing to the output stream) in the sed file itself? Redirecting the cmd command and the error stream to nul doesn't seem to suppress the command itself from showing up. I'm guessing because it's being sent to stdin, maybe? If so, it looks like there are solutions for this, but they can get pretty complicated:
http://stackoverflow.com/questions/664957/can-i-mask-an-input-text-in-a-bat-file
Edit: that article, after rereading it, doesn't do what I think it does. Still searching for the type of behavior  intended..

**Comment by nickrod518** [comment] 2016-04-20 22:01
I wonder if it might be simpler than that... I'm not at a computer but what if you further edit that line to launch the PS file in a new window? Adding something like `start` or `cmd /c` in front of the call to PowerShell? That way the original window with the text you don't want displayed is used to launch the PS script and then hidden.

**Comment by nickrod518** [comment] 2016-04-20 22:03
It's also interesting that it's not the whole cmd that's displayed, just what's after `do` ...

**Comment by j-sabrsula** [comment] 2016-04-21 14:08
Agreed, it's interesting what is chosen as output and just 'processable input' out of that single line. I've tried start and cmd /c (and both) at the powershell part of that add content line, have not been successful in suppressing the output (when the window displays at all). I've been trying to see if @ or @Echo off works, haven't found the right combination to make this possible either.

**Comment by nickrod518** [comment] 2016-04-25 13:28
found sort of a solution... "...do PowerShell -WindowStyle Hidden..."

Have you run into any weird issues that should keep me from publishing this change for everyone?

**Comment by j-sabrsula** [comment] 2016-04-25 13:53
I'm not sure i'm getting the same results as you- 

Here's the code:
![image](https://cloud.githubusercontent.com/assets/11077362/14786089/f7b084be-0ac2-11e6-9a22-555140bef4f2.png)

And here's the script i'm running, (I get a blank window when trying to run the exe) 
![image](https://cloud.githubusercontent.com/assets/11077362/14786110/0b360374-0ac3-11e6-93a2-274f2b87aa80.png)

Expected result- path will be displayed
Actual result-
![image](https://cloud.githubusercontent.com/assets/11077362/14786142/24f970f2-0ac3-11e6-9857-94629ebc3740.png)

This is on Win 7 and Win Server 2012 R2 both

**Comment by nickrod518** [comment] 2016-04-25 14:08
I believe you replaced the wrong lines. You want to replace the line under the comment "# After we've..." with:
`cmd /c for /f `"skip=1 tokens=1* delims=`" %i in (`'wmic process where `"name=`'$target.exe`'`" get ExecutablePath`') do PowerShell -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$PSScriptName`" `"%i`" & exit"`

and then the line in the `else` block with:
`cmd /c for /f `"skip=1 tokens=1* delims=`" %i in (`'wmic process where `"name=`'$target.exe`'`" get ExecutablePath`') do PowerShell -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$PSScriptName`" `"%i`" & exit"`

**Comment by j-sabrsula** [comment] 2016-04-25 14:20
Whoops, thanks, you're right. I corrected it and tried but the window opens and then closes without displaying the path, just the command after the 'do' statement briefly, before exiting.  
![image](https://cloud.githubusercontent.com/assets/11077362/14786847/671a6f38-0ac6-11e6-8f2f-3ba4d259d478.png)

It sounds like i've got the syntax wrong still, possibly?

**Comment by nickrod518** [comment] 2016-04-25 16:02
I was wrong about that, you couldn't see it because it was hiding the powershell window, so it was actually working correctly but not for what we want. I came up with a simpler solution - change the line to:
`cmd /c for /f `"skip=1 tokens=1* delims=`" %i in (`'wmic process where `"name=`'$target.exe`'`" get ExecutablePath`') do PowerShell -WindowStyle Hidden -ExecutionPolicy Bypass -Command Clear-Host; `"$PSScriptName`" `"%i`" & exit"`

**Comment by nickrod518** [comment] 2016-04-25 16:23
FYI, I'm moving this project to its own repo - https://github.com/nickrod518/Create-EXEFromPS1

**Comment by j-sabrsula** [comment] 2016-04-25 16:29
Thanks, I tried the code in the new repo, and it's working in the test script as intended. (great work) If I find anything new regarding errors or compatibility concerns, i'll let you know.

**Comment by nickrod518** [comment] 2016-04-25 16:48
So glad to hear it!
On Apr 25, 2016 12:29 PM, j-sabrsula notifications@github.com wrote:Thanks, I tried the code in the new repo, and it's working in the test script as intended. (great work) If I find anything new regarding errors or compatibility concerns, i'll let you know.

**Closed as completed** 2016-04-25 20:44 UTC
Labels: enhancement
